#ifndef _COLORS_H
#define _COLORS_H

#include <curses.h>

#define COLOR_BLACK_FG 1
#define COLOR_GREEN_FG 2
#define COLOR_WHITE_FG 3
#define COLOR_RED_FG 4 
#define COLOR_CYAN_FG 5
#define COLOR_MAGENTA_FG 6
#define COLOR_BLUE_FG 7
#define COLOR_YELLOW_FG 8

#define COLOR_BLACK_BG 9
#define COLOR_GREEN_BG 10
#define COLOR_WHITE_BG 11
#define COLOR_RED_BG 12 
#define COLOR_CYAN_BG 13
#define COLOR_MAGENTA_BG 14
#define COLOR_BLUE_BG 15
#define COLOR_YELLOW_BG 16

void init_colors(){
    start_color();
	
	init_pair(COLOR_BLACK_BG, COLOR_WHITE, COLOR_BLACK);
	init_pair(COLOR_GREEN_BG, COLOR_WHITE, COLOR_GREEN);
	init_pair(COLOR_WHITE_BG, COLOR_BLACK, COLOR_WHITE);
	init_pair(COLOR_RED_BG, COLOR_WHITE, COLOR_RED);
	init_pair(COLOR_CYAN_BG, COLOR_WHITE, COLOR_CYAN);
	init_pair(COLOR_MAGENTA_BG, COLOR_WHITE, COLOR_MAGENTA);
	init_pair(COLOR_BLUE_BG, COLOR_WHITE, COLOR_BLUE);
	init_pair(COLOR_YELLOW_BG, COLOR_WHITE, COLOR_YELLOW);

	init_pair(COLOR_BLACK_FG, COLOR_BLACK, COLOR_BLACK);
	init_pair(COLOR_GREEN_FG, COLOR_GREEN, COLOR_BLACK);
	init_pair(COLOR_WHITE_FG, COLOR_WHITE, COLOR_BLACK);
	init_pair(COLOR_RED_FG, COLOR_RED, COLOR_BLACK);
	init_pair(COLOR_CYAN_FG, COLOR_CYAN, COLOR_BLACK);
	init_pair(COLOR_MAGENTA_FG, COLOR_MAGENTA, COLOR_BLACK);
	init_pair(COLOR_BLUE_FG, COLOR_BLUE, COLOR_BLACK);
	init_pair(COLOR_YELLOW_FG, COLOR_YELLOW, COLOR_BLACK);
}

#endif